application:
  name: @name@
  version: @version@

spring:
  application:
    name: ${application.name}

camel:
  springboot:
    main-run-controller: true

datasource:
  url: jdbc:mysql://172.18.107.238/sso?useTimezone=false&serverTimezone=UTC
  port: 3306
  user: frota
  password: frota

rjconsultores:
  url: 34.198.151.111:9991/WSMonitriip/busca/buscaServico
  authorization: Basic bTJtOnJqbTJtcmo= # credenciais para autenticação Http Basic do webservice rjconsultores
  consumer-period: 10s # período que o serviço irá dormir até realizar a próxima consulta

server:
  port: 8989
  max-threads: 100

mongo:
  host: localhost
  port: 27017
  database: monitriip_znh

url-zona: http://znd2.m2mcontrol.com.br/#/

external-resources: src/main/resources/files

logging:
  file: /var/log/m2m-monitriip-worker-servicos.log
